name: Builder Application
description: Apply to become a builder on the JeriCraft Minecraft server.
title: "Builder Application for: <name>"
labels: [ "Builder Application" ]
assignees: Chalwk77
body:
  - type: markdown
    attributes:
      value: |
        This form is intended for individuals interested in applying for a builder position.
        Please take your time to provide detailed and accurate information.
        
        Please note that we will review applications as soon as possible, and you will be contacted if your application is selected for further consideration.

        # JeriCraft Builder Requirements:

        - Must be 13 or older.
        - Must be an active member of the community for at least 1.5 months.
        - Have at least 50 hours of playtime on the server.
        - You are allowed to build in pairs.
          > *Collaborations with the intent of using your build for this application require that 70% of the build be done by you.*
        - Builds must be original and not copied from the internet.
        - We require a minimum of 3 separate builds to be submitted for review.
          > *These builds must be done on the server and have different styles and themes.*
          > *You must provide the coordinates of each build.*
          > *Creative mode and World Edit are for Personal use only! You are not permitted to build for other players, period.*
        
        ---
        
        **While in creative mode:**
          - You will not be able to pick up or drop items.
          - You will not be able to access (or place) anything with an inventory. I.e. chests, furnaces, dispensers, etc.
          - Certain commands will become disabled for you. Such as /sell hand and /ah sell.
          - Your creative inventory will be separate from your survival inventory.

        ---

        **Restricted access to World Edit:**
          - World Edit will be limited to regions that you own.
          - Make sure you set the `worldedit allow` flag in your region before performing World Edit operations.
          - Certain commands will be disabled for you. See the [Player Commands](https://github.com/Chalwk77/JeriCraftDocs/blob/main/docs/commands/PLAYER-COMMANDS.md) for more information.

        ---
        ## IMPORTANT:
        - You are required to have Discord for communication purposes.
        - ðŸ“ Must read and agree to our [community rules](https://github.com/Chalwk77/JeriCraftDocs/blob/main/docs/about-jericraft/Community%20Rules.md).
        - âš ï¸Do not make an application if you don't meet these requirements. You will be denied.âš ï¸ï¸
        
        ---
  - type: checkboxes
    id: accept-rules
    attributes:
      label: Do you accept our community rules?
      description: Please read and accept our community rules before proceeding.
      options:
        - label: Yes ðŸ‘
        - label: No âŒ
  - type: input
    id: minecraft-discord-username
    attributes:
      label: ðŸŽ® Minecraft/Discord Username
      description: Provide your Minecraft and Discord usernames.
      placeholder: "Your Minecraft and Discord Usernames"
    validations:
      required: true
  - type: input
    id: age
    attributes:
      label: ðŸŽ‚ Age
      description: How old are you?
      placeholder: "*You must be 13 years or older to apply for Builder.*"
    validations:
      required: true
  - type: input
    id: timezone
    attributes:
      label: â° Time Zone
      description: What is your time zone?
      placeholder: "*Please provide your timezone (e.g. UTC-5, GMT+1, etc.).*"
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: ðŸŒŽ Country
      description: What country do you live in?
      placeholder: "Your country"
    validations:
      required: true
  - type: input
    id: community-duration
    attributes:
      label: â° Community Duration
      description: How long have you been a member of the JeriCraft community?
      placeholder: "Your community duration"
    validations:
      required: true
  - type: input
    id: planet-minecraft
    attributes:
      label: ðŸ“° Planet Minecraft Account
      description: Do you have a Planet Minecraft (PMC) account?
      placeholder: "Your PMC account (if applicable)"
    validations:
      required: true
  - type: textarea
    id: account-access
    attributes:
      label: ðŸ‘¥ Account Access
      description: Does anyone else have access to your Minecraft account?
      placeholder: "Explain if anyone else has access to your account."
    validations:
      required: true
  - type: textarea
    id: why-builder
    attributes:
      label: ðŸ—¿ Why do you think you should become a builder?
      description: Explain why you think you should become a builder on the JeriCraft server.
      placeholder: "Write your reason here"
    validations:
      required: true
  - type: textarea
    id: previous-builds
    attributes:
      label: â˜­ Previous Builds
      description: Have you built anything on JeriCraft before?
      placeholder: "Explain if you have built anything on JeriCraft before."
    validations:
      required: true
  - type: textarea
    id: building-style
    attributes:
      label: ðŸ”¨ Building Style
      description: What is your preferred building style?
      placeholder: "E.g. Modern, Medieval, Fantasy, etc."
    validations:
      required: true
  - type: textarea
    id: world-edit-experience
    attributes:
      label: ðŸ’¡ World Edit Experience
      description: Do you have any experience with World Edit?
      placeholder: "Explain your experience with World Edit."
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **ðŸ“· Screenshots**
        > Include screenshots of your builds on the JeriCraft server.
        > Provide the coordinates of each build so we can review them.
        >
        > ðŸ™Œ Thank you
        >
        > **We appreciate your effort in applying for a builder position on the JeriCraft server. Your input is invaluable!**