name: Staff Application
description: Apply to become a staff member on the server.
title: 'Staff Application - [Your Name]'
labels:
  - staff-application
  - pending
  - awaiting-review
  - awaiting-interview
assignees: Chalwk77
body:
  - type: markdown
    attributes:
      value: |
        This form is intended for individuals interested in applying for a staff position at JeriCraft. Please take your time to provide detailed and accurate information.
        
        Please note that we will review applications as soon as possible, and you will be contacted if your application is selected for further consideration. We appreciate your interest in joining the JeriCraft staff team!

        **JeriCraft Staff Requirements:**

        - Must be 17 or older.
        - ðŸ•’ Must be an active member of the community for at least 3 months.
        - â° Have at least 100 hours of playtime on the server.
        - â±ï¸ Be able to dedicate at least 5 hours a week to the server.
        - ðŸŽ® Must have a Discord account for communication purposes.
        - ðŸŽ¤ Must have a working microphone.
        - ðŸ“ Must read and agree to our [community rules](https://github.com/Chalwk77/JeriCraftDocs/blob/main/docs/about-jericraft/Community%20Rules.md).
        - âš ï¸Do not make an application if you don't meet these requirements. You will be denied.âš ï¸ï¸
        
        ---
        
        # Staff Rank Hierarchy:
        - ðŸµï¸ **Trial-Mod (Trial Moderator)**
        > As an entry-level staff rank, Trial-Mods have access to essential moderation commands (âœ¨) to help maintain the server's friendly environment.
        
        - ðŸ› ï¸ **Moderator**
        > Moderators have access to all Trial-Mod commands and additional tools (ðŸ”§) for managing and resolving issues efficiently.
        
        - âš™ï¸ **Admin (Administrator)**
        > Admins have access to all Moderator and Trial-Mod commands, along with advanced tools (âš™ï¸) for server management and behind-the-scenes operations.
        
        - ðŸ‘‘ **Owner / Senior Admin**
        > The highest rank in the JeriCraft hierarchy, Owners have access to all staff commands (ðŸ‘‘) and are responsible for overseeing the entire server.
        
        ## Staff Commands:
        Please familiarize yourself with the [staff commands](https://github.com/Chalwk77/JeriCraftDocs/blob/main/docs/commands/STAFF-COMMANDS.md)
        These commands are essential for moderating the server and resolving player-related issues.
        
        ---
  - type: checkboxes
    id: accept-rules
    attributes:
      label: Do you accept our community rules?
      description: Please read and accept our community rules before proceeding.
      options:
        - label: Yes ðŸ‘
        - label: No âŒ
  - type: input
    id: minecraft-discord-username
    attributes:
      label: ðŸŽ® Minecraft/Discord Username
      description: Provide your Minecraft and Discord usernames.
      placeholder: "Your Minecraft and Discord Usernames"
    validations:
      required: true
  - type: textarea
    id: about-yourself
    attributes:
      label: ðŸ™‹ï¸ Tell us about yourself
      description: Provide a brief introduction about yourself.
      placeholder: "Tell us about yourself"
    validations:
      required: true
  - type: input
    id: age
    attributes:
      label: ðŸŽ‚ Age
      description: How old are you?
      placeholder: "Your age"
    validations:
      required: true
  - type: input
    id: timezone
    attributes:
      label: ðŸŒ Timezone
      description: What is your timezone?
      placeholder: "*Please provide your timezone (e.g. UTC-5, GMT+1, etc.).*"
    validations:
      required: true
  - type: textarea
    id: account-access
    attributes:
      label: Does anyone else have access to your Minecraft account?
      description: This is important for security reasons. If yes, please explain, otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: minecraft-experience
    attributes:
      label: ðŸŽ® Minecraft Experience
      description: Tell us about your experience with Minecraft, including any previous staff positions you've held.
    validations:
      required: true
  - type: textarea
    id: contribution
    attributes:
      label: ðŸŽ What will you provide to our community if granted moderator status?
      description: Explain what you can offer to the community as a staff member.
    validations:
      required: true
  - type: textarea
    id: availability
    attributes:
      label: ðŸ•’ Availability
      description: Provide your availability and the hours you can dedicate to the server.
      placeholder: "Your availability"
    validations:
      required: true
  - type: textarea
    id: hacked-client
    attributes:
      label: ðŸš« Have you ever used a hacked client before?
      description: If yes, please explain. Otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: minecraft-ban
    attributes:
      label: â›” Have you ever been banned on a Minecraft server?
      description: If yes, please explain. Otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: strengths-weaknesses
    attributes:
      label: ðŸ’ª What are your strengths and weaknesses?
      description: Provide details about your strengths and weaknesses.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # ðŸš¨ Scenario Questions (test your knowledge):
        > This is a test to see if you understand the rules and how to handle situations as a staff member.
        
        ---

  - type: textarea
    id: scenario_1
    attributes:
      label: 1. You observe a player using unauthorized mods, such as fly mod or X-ray, to gain an unfair advantage.
      description: How would you handle this situation and ensure fair play on the server?
    validations:
      required: true
  - type: textarea
    id: scenario_2
    attributes:
      label: 2. A player is sharing links and promoting another server in the chat, attempting to divert players away from your server.
      description: How would you address this issue and enforce the server's rules?
    validations:
      required: true
#  - type: textarea
#    id: scenario_2
#    attributes:
#      label: ðŸš¨ A player is sharing links and promoting another server in the chat, attempting to divert players away from your server.
#      description: How would you address this issue and enforce the server's rules?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_3
#    attributes:
#      label: ðŸš¨ A player is repeatedly sending messages in quick succession, disrupting the chat, and causing frustration for other players.
#      description: How would you intervene and maintain a positive chat environment?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_4
#    attributes:
#      label: ðŸš¨ You notice a player using disrespectful language or behavior towards staff members or other players.
#      description: What steps would you take to address their actions and promote a friendly community atmosphere?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_5
#    attributes:
#      label: ðŸš¨ A player is intentionally destroying or vandalizing another player's build without permission.
#      description: How would you manage this situation and ensure that players' hard work is protected?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_6
#    attributes:
#      label: ðŸš¨ A player reports a bug or glitch in the game.
#      description: How would you handle this situation?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_7
#    attributes:
#      label: ðŸš¨ Two players are arguing in chat, and it's starting to disrupt the community.
#      description: How would you intervene and resolve the conflict?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_8
#    attributes:
#      label: ðŸš¨ You notice a player has found a loophole in the rules.
#      description: What steps would you take to address the issue and update the rules?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_9
#    attributes:
#      label: ðŸš¨ A new player is having difficulty understanding the rules or navigating the server.
#      description: How would you assist them?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_10
#    attributes:
#      label: ðŸš¨ A player claims they were falsely punished by another staff member.
#      description: How would you approach this situation?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_11
#    attributes:
#      label: ðŸš¨ A player accuses a staff member of abusing their powers.
#      description: How would you handle this situation and ensure fairness?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_12
#    attributes:
#      label: ðŸš¨ You receive multiple reports of players using unauthorized mods.
#      description: How would you investigate the issue and enforce the rules?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_13
#    attributes:
#      label: ðŸš¨ The server is experiencing a significant drop in player activity.
#      description: How would you work with the staff team to identify the cause and boost engagement?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_14
#    attributes:
#      label: ðŸš¨ A player is found to be account sharing.
#      description: What actions would you take to address the issue?
#      placeholder: ""
#    validations:
#      required: true
#  - type: textarea
#    id: scenario_15
#    attributes:
#      label: ðŸš¨ A group of players is using the server for purposes not aligned with its intended use (e.g., inappropriate roleplay).
#      description: How would you handle this situation?
#      placeholder: ""
#    validations:
#      required: true