name: Staff Application
description: Apply to become a staff member on the server.
title: 'Staff Application - [Your Name]'
labels:
  - staff-application
  - pending
  - awaiting-review
  - awaiting-interview
assignees: Chalwk77
body:
  - type: markdown
    attributes:
      value: |
        This form is intended for individuals interested in applying for a staff position at JeriCraft. Please take your time to provide detailed and accurate information.
        
        Please note that we will review applications as soon as possible, and you will be contacted if your application is selected for further consideration. We appreciate your interest in joining the JeriCraft staff team!
        
        We are recruiting!

        **JeriCraft Staff Requirements:**

        - Must be 17 or older.
        - ðŸ•’ Must be an active member of the community for at least 3 months.
        - â° Have at least 100 hours of playtime on the server.
        - â±ï¸ Be able to dedicate at least 5 hours a week to the server.
        - ðŸŽ¤ Must have a working microphone.
        - ðŸ“ Must read and agree to our [community rules](https://github.com/Chalwk77/JeriCraftDocs/blob/main/docs/about-jericraft/Community%20Rules.md).
        - Must have a Discord account for communication purposes.

        **âš ï¸Do not make an application if you don't meet these requirements. You will be denied.âš ï¸ï¸**
        
        - ðŸµï¸ **Trial-Mod (Trial Moderator)**: As an entry-level staff rank, Trial-Mods have access to essential moderation
        commands (âœ¨) to help maintain the server's friendly environment.

        - ðŸ› ï¸ **Moderator**: Moderators have access to all Trial-Mod commands and additional tools (ðŸ”§) for managing and resolving
          issues efficiently.
        
        - âš™ï¸ **Admin (Administrator)**: Admins have access to all Moderator and Trial-Mod commands, along with advanced tools (âš™ï¸)
          for server management and behind-the-scenes operations.
        
        - ðŸ‘‘ **Owner**: The highest rank in the JeriCraft hierarchy, Owners have access to all staff commands (ðŸ‘‘) and are
          responsible for overseeing the entire server. Each staff rank inherits the commands and permissions of the ranks below
          it, ensuring an organized and efficient staff structure for the best possible player experience.
          ---
  - type: checkboxes
    id: accept-rules
    attributes:
      label: Do you accept our community rules?
      description: Please read and accept our community rules before proceeding.
      options:
        - label: Yes ðŸ‘
        - label: No âŒ
  - type: input
    id: minecraft-discord-username
    attributes:
      label: ðŸŽ® Minecraft/Discord Username
      description: Provide your Minecraft and Discord usernames.
      placeholder: "Your Minecraft and Discord Usernames"
    validations:
      required: true
  - type: textarea
    id: about-yourself
    attributes:
      label: ðŸ™‹ï¸ Tell us about yourself
      description: Provide a brief introduction about yourself.
      placeholder: "Tell us about yourself"
    validations:
      required: true
  - type: input
    id: age
    attributes:
      label: ðŸŽ‚ Age
      description: How old are you?
      placeholder: "Your age"
    validations:
      required: true
  - type: input
    id: timezone
    attributes:
      label: ðŸŒ Timezone
      description: What is your timezone?
      placeholder: "*Please provide your timezone (e.g. UTC-5, GMT+1, etc.).*"
    validations:
      required: true
  - type: textarea
    id: account-access
    attributes:
      label:  Does anyone else have access to your Minecraft account?
      description: This is important for security reasons. If yes, please explain, otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: minecraft-experience
    attributes:
      label: ðŸŽ® Minecraft Experience
      description: Tell us about your experience with Minecraft, including any previous staff positions you've held.
    validations:
      required: true
  - type: textarea
    id: contribution
    attributes:
      label: ðŸŽ What will you provide to our community if granted moderator status?
      description: Explain what you can offer to the community as a staff member.
    validations:
      required: true
  - type: textarea
    id: availability
    attributes:
      label: ðŸ•’ Availability
      description: Provide your availability and the hours you can dedicate to the server.
      placeholder: "Your availability"
    validations:
      required: true
  - type: textarea
    id: hacked-client
    attributes:
      label: ðŸš« Have you ever used a hacked client before?
      description: If yes, please explain. Otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: minecraft-ban
    attributes:
      label: â›” Have you ever been banned on a Minecraft server?
      description: If yes, please explain. Otherwise, type "No".
    validations:
      required: true
  - type: textarea
    id: strengths-weaknesses
    attributes:
      label: ðŸ’ª What are your strengths and weaknesses?
      description: Provide details about your strengths and weaknesses.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **ðŸ“Œ Scenario Questions (test your knowledge)**
        > This is a test to see if you understand the rules and how to handle situations as a staff member.
        > 1. *Someone is hacking (fly mod, x-ray, etc.), what do you do?*
        > 2. *Someone is advertising another server. What do you do?*
        > 3. Someone is spamming in chat, what do you do?
        > 4. Someone is being disrespectful to staff or other players, what do you do?
        > 5. Someone is griefing another player's build, what do you do?
  - type: textarea
    id: scenarios
    attributes:
      label: ðŸš¨ Scenarios
      description: Answer the following scenario questions.
      placeholder: "Answer the following scenario questions."
    validations:
      required: true